# This workflow represents a set of basic cmds
on:
  push:
    branches:
      - 'main'

jobs:

  basic-ubuntu-20:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
    run: echo "running a sample action file"
