---
name: sample Workflow
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout action
      - uses: actions/checkout@v4
        run: echo "checkout trigger"
      - name: Simulating error
        run: echo "error in this line and exit"; exit 1
