# This workflow represents a set of basic cmds
name: sample Workflow

# Trigger Events
on:
  push:
    branches:
      - 'main'
      
# Jobs for this workflow
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout action
      - uses: actions/checkout@v4  # push trigger' 1st step
        run: echo "checkout trigger"

      - name: Simulating error
        run: echo "error in this line and exit"; exit 1


